services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - cephid-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GRPC_HOST=backend:9090
    depends_on:
      - backend
    networks:
      - cephid-network
    restart: on-failure

networks:
  cephid-network:
    driver: bridge
